trigger:
- '*'

jobs:
- job: FirstJob
  displayName: 'First Job'
  steps:
  - script: echo "This is the first job"
    displayName: 'Run First Job'

- job: SecondJob
  displayName: 'Second Job'
  steps:
  - script: echo "This is the second job"
    displayName: 'Run Second Job'

- job: ThirdJob
  displayName: 'Third Job'
  steps:
  - script: echo "This is the third job"
    displayName: 'Run Third Job'
