trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # Specify the agent pool and VM image

stages:
- stage: MyStage
  jobs:
  - job: test
    steps:
    - template: RunMyJob.yml  # First template
      parameters:
        param1: 'value1'
        param2: 'value2'
        jobname: 'sachin'

    
  - job: test2 
    dependsOn: test
    steps:
    - template: RunMyJob.yml  # First template
      parameters:
        param1: 'value1'
        param2: 'value2'
        jobname: 'ganguly'
