
trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # Specify the agent pool and VM image

stages:
- stage: MyStage
  jobs:
  - deployment: Approval
    environment: 'DEV_ENV'
  - template: RunMyJob.yml
    parameters:
      param1: 'value1'
      param2: 'value2'
      param3: '-new'
      jobname: 'sachin'
      india: 'canada'

- stage: MyStage1
  jobs:
  - template: RunMyJob1.yml
    parameters:
      param1: 'value1'
      param2: 'value2'
      jobname: 'sachin'
      india: 'canada'
  
 
