parameters:
  # Define the variable groups to use
  - name: variableGroups
    type: object
    default:
      - name: "Customer"
        variableGroupName: "Customer variables"
      - name: "Test"
        variableGroupName: "Test variables"

pool:
  vmImage: 'windows-latest'

stages:
  - stage: "test_stage"
    jobs:
      # Run the job for each variable group
      - ${{ each variableGroup in parameters.variableGroups }}:
          - job: "run_for_each_${{ variableGroup.name }}_variable_group_job"
            displayName: "Using ${{ upper(variableGroup.name) }} variable group"
            variables:
              - group: ${{ variableGroup.variableGroupName }}
            steps:
              - script: echo $(MyVariable)
