trigger:
- '*'

jobs:
- job: FirstJob
  displayName: 'First Job'
   - template: RunMyJob.yml
     parameters:
       param1: 'value1'
       param2: 'value2'
       jobname: 'sachin'

- job: SecondJob
  displayName: 'Second Job'
   - template: RunMyJob.yml
     parameters:
       param1: 'value1'
       param2: 'value2'
       jobname: 'gan'

