
#jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: RunMyJob.yml  # Template reference
    parameters:
      scriptParam1: 'value1'
      scriptParam2: 'value2'
    
  - template: RunMyJob.yml  # Template reference
    parameters:
      scriptParamA: 'value1'
      scriptParamB: 'value2'
