trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # Specify the agent pool and VM image

stages:
- stage: MyStage
  jobs:
  - job: ${{ parameters.jobname }}
    steps:
    - template: RunMyJob.yml  # First template
       parameters:
         param1: 'value1'
         param2: 'value2'
         jobname: 'sachin'

    
  - job: ${{ parameters.jobname }} 
    dependsOn:
    steps:
    - template: RunMyJob.yml  # First template
       parameters:
         param1: 'value1'
         param2: 'value2'
         jobname: 'ganguly'
