
trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # Specify the agent pool and VM image

stages:
- stage: MyStage
  jobs:
  - job: Job1
    steps:
    - script: echo "This is Job 1"
    
  - job: Job2
    steps:
    - script: echo "This is Job 2"
