trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'  # Specify the agent pool and VM image

stages:
- stage: MyStage
  jobs:
  -job: build
  - template: RunMyJob.yml
    parameters:
      param1: 'value1'
      param2: 'value2'
      jobname: 'sachin'

  - job: test
  - template: RunMyJob.yml
    parameters:
      paramA: 'value1'
      paramB: 'value2'
      jobname: 'ganguly' 
