jobs:
- job: MyJob
  steps:
  - template: script-template1.yml  # Include the first script template
    parameters:
      scriptParam1: 'value1'
      scriptParam2: 'value2'
      
  - template: script-template2.yml  # Include the second script template
    parameters:
      scriptParamA: 'valueA'
      scriptParamB: 'valueB'