jobs:
- job: MultiRunJob
  strategy:
    matrix:
      os:   [ 'windows', 'linux' ]
      env:  [ 'dev', 'test', 'prod' ]
  steps:
  - template: RunMyJob.yml  # Include a job template file
    parameters:
      os: ${{ matrix.os }}
      environment: ${{ matrix.env }}
