
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: RunMyJob.yml  # Template reference
    scriptParam1: 'value1'
    scriptParam2: 'value2'
    
  - template: RunMyJob.yml  # Template reference
    scriptParamA: 'value1'
    scriptParamB: 'value2'
