parameters:
  scriptParam1: ''
  scriptParam2: ''
  jobname: ''
  india: ''
  
jobs:
  - job: ${{ parameters.jobname }}
    steps:
      - script: echo "This is the ${{ parameters.jobname }} job"
      
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'install Node.js'

      
     
