parameters:
  scriptParam1: 'value1'
  scriptParam2: 'value2'
  
jobs:
  - job: BUILD_AND_DEPLOY
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'install Node.js'
