parameters:
  scriptParam1: ''
  scriptParam2: ''
  jobname: ''
  india: ''
  
jobs:
  - job: ${{ parameters.jobname }}
    steps:
      - script: echo "This is the ${{ parameters.jobname }} job"
      
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'install Node.js'

      - template: test.yml
        parameters:
          india: '${{ parameters.india }}'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/outt
          artifactName: 'out'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/outt
          artifactName: 'outt'

      


          

      
     
