parameters:
  scriptParam1: ''
  scriptParam2: ''
  jobname: ''
  india: ''
  
jobs:
  - job: ${{ parameters.jobname }}
    steps:
      - script: echo "This is the ${{ parameters.jobname }} job"

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'outt'
          targetPath: '$(System.DefaultWorkingDirectory)/out'

      - task: CmdLine@2
        inputs:
          script: 'ls -lrt $(System.DefaultWorkingDirectory) && ls -lrt $(System.DefaultWorkingDirectory)/out'

      
     
